### PR TITLE
Changes as per interface dir structure

### PR DESCRIPTION
**Pull request by kavitharaju**
- Add a new directory `core`, to keep the core logics of the app
   ```
   assistant.bible/app/core
   ├── __ init __.py
   ├── auth
   │   └── __ init __.py
   ├── embedding
   │   ├── __ init __.py # contains interface definitions
   │   └── openai.py
   ├── llm_framework
   │   ├── __ init __.py # contains interface definitions
   │   ├── langchain.py
   │   └── vanilla.py
   ├── pipeline
   │   ├── __ init __.py # contains interface definitions
   │   ├── langchain_stack.py
   │   └── vanilla_stack.py
   └── vectordb
       ├── __ init __.py # contains interface definitions
       └── chroma.py
  ```
- Move all endpoint definitions out of main.py. Keep them in `assistant.bible/app/routers.py`

### CODE REVIEW

**Comment by joelthe1** [comment]
@kavitharaju, thanks for putting this together. I think it makes sense. I might only change the `llm_framework/langchain.py` to something like `llm_framework/openai_langchain.py` and the other one to `llm_framework/openai_vanilla.py`.

**Review by woodwardmw — APPROVED** [review]
Yep, that looks good to me.

**Comment by kavitharaju** [comment]
> change the llm_framework/langchain.py to something like llm_framework/openai_langchain.py and the other one to llm_framework/openai_vanilla.py.

This change made in #9

**Comment by woodwardmw** [comment]
@joelthe1 @kavitharaju I think we can go ahead and merge this. I don't see the merge button, so I guess I don't have permission to do it...

**Comment by kavitharaju** [comment]
@woodwardmw This PR is already merged. The new one is here #9

**Pull request merged**
